/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CCScrollView.jsb.ini" on 2012-12-01
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CCSCROLLVIEW

#import "CCScrollView.h"
#import "js_bindings_cocos2d_ios_classes.h"

/*
 * CCScrollView
 */
#pragma mark - CCScrollView

#ifdef __cplusplus
extern "C" {
#endif

void JSB_CCScrollView_createClass(JSContext *cx, JSObject* globalObj, const char* name );



extern JSObject *JSB_CCScrollView_object;
extern JSClass *JSB_CCScrollView_class;

#ifdef __cplusplus
}
#endif

/* Proxy class */
@interface JSB_CCScrollView : JSB_CCLayer
{
}
@end


#endif // JSB_INCLUDE_CCSCROLLVIEW
