/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_js_bindings.py -c CCScrollView.jsb.ini" on 2012-12-01
* Script version: v0.3
*/
#import "js_bindings_config.h"
#ifdef JSB_INCLUDE_CCSCROLLVIEW

#import "CCScrollView.h"
#import "js_bindings_cocos2d_ios_classes.h"
JSB_CCScrollView_createClass(_cx, CCScrollView, "ScrollView");


#endif // JSB_INCLUDE_CCSCROLLVIEW
